using Avalonia.Media.Imaging;
using DxfToSvg.Core.Pipeline;

namespace DXF_Converter_GUI.ViewModels;

/// <summary>A pipeline node that holds one <see cref="Artifact"/> and exposes the operations every
/// preview shares: show an autogenerated preview, rotate the artifact, and download it. The shared
/// <c>PreviewPanel</c> control binds to this, so any node — DXF, SVG, PNG, or a future format —
/// gets the same UI without duplication.</summary>
public interface IPreviewNode
{
    /// <summary>Node label, e.g. "DXF".</summary>
    string Title { get; }

    /// <summary>Name of the file this node was loaded from, or null when produced by a transition.</summary>
    string? FileName { get; }

    /// <summary>Autogenerated preview image, or null when the node is empty / can't be rendered.</summary>
    Bitmap? Preview { get; }

    /// <summary>The current artifact (bytes + format), or null when empty. Used for download.</summary>
    Artifact? Artifact { get; }

    /// <summary>Suggested base file name (no extension) for downloads.</summary>
    string SuggestedBaseName { get; }

    bool HasArtifact { get; }

    /// <summary>True when a same-format rotate transition is registered for this node's format.</summary>
    bool CanRotate { get; }

    /// <summary>Rotates the artifact 90° clockwise in place (regenerating the preview).</summary>
    void RotateClockwise();
}
