using System;
using System.IO;
using Avalonia.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using DXF_Converter_GUI.Services;
using DxfToSvg.Core;

namespace DXF_Converter_GUI.ViewModels;

/// <summary>Drives the pipeline as three data nodes — DXF, SVG, PNG — joined by two
/// transitions (DXF → SVG, SVG → PNG). Each node can also be uploaded directly.
///
/// The stored data model is <em>the pipeline artifacts and transition parameters only</em>
/// (<see cref="DxfPath"/>, <see cref="SvgContent"/>, <see cref="PngBytes"/>, <see cref="FillColor"/>,
/// <see cref="PngWidth"/>). The three preview bitmaps are always regenerated from that data whenever
/// it changes — see the <c>OnXChanged</c> hooks — and are never assigned from anywhere else.</summary>
public partial class MainWindowViewModel : ObservableObject
{
    private const int PreviewWidth = 640;

    private const string FillColorKey = "FillColor";
    private const string PngWidthKey = "PngWidth";

    private readonly UserPersistentData _settings = new("settings");

    /// <summary>Guards against writing back to disk while the constructor applies loaded values.</summary>
    private readonly bool _loaded;

    public MainWindowViewModel()
    {
        if (_settings.TryLoad(FillColorKey, out string? fill) && !string.IsNullOrWhiteSpace(fill))
        {
            FillColor = fill;
        }
        if (_settings.TryLoad<int>(PngWidthKey, out int width) && width > 0)
        {
            PngWidth = width;
        }
        _loaded = true;
    }

    // ---- Data model: pipeline artifacts (the nodes) ----

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasDxf))]
    [NotifyPropertyChangedFor(nameof(CanConvertToSvg))]
    [NotifyPropertyChangedFor(nameof(DxfFileName))]
    private string? _dxfPath;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasSvg))]
    [NotifyPropertyChangedFor(nameof(CanConvertToPng))]
    private string? _svgContent;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasPng))]
    private byte[]? _pngBytes;

    // ---- Data model: transition parameters ----

    [ObservableProperty]
    private string _fillColor = Converter.DefaultFill;

    [ObservableProperty]
    private int _pngWidth = 813;

    // ---- Autogenerated previews (derived from the data above; see OnXChanged hooks) ----

    [ObservableProperty]
    private Bitmap? _dxfPreview;

    [ObservableProperty]
    private Bitmap? _svgPreview;

    [ObservableProperty]
    private Bitmap? _pngPreview;

    [ObservableProperty]
    private string _status = "Upload a DXF, SVG, or PNG to begin.";

    /// <summary>File name (without extension) of the most recently loaded input, used to
    /// suggest download names.</summary>
    public string? SourceBaseName { get; private set; }

    public string? DxfFileName => DxfPath is null ? null : Path.GetFileName(DxfPath);

    public bool HasDxf => !string.IsNullOrEmpty(DxfPath);
    public bool HasSvg => !string.IsNullOrEmpty(SvgContent);
    public bool HasPng => PngBytes is not null;
    public bool CanConvertToSvg => HasDxf;
    public bool CanConvertToPng => HasSvg;

    // ---- Preview regeneration: the ONLY places the preview bitmaps are assigned ----

    partial void OnDxfPathChanged(string? value) => RegenerateDxfPreview();
    partial void OnSvgContentChanged(string? value) => RegenerateSvgPreview();
    partial void OnPngBytesChanged(byte[]? value) => RegeneratePngPreview();

    private void RegenerateDxfPreview()
    {
        if (string.IsNullOrEmpty(DxfPath))
        {
            DxfPreview = null;
            return;
        }
        try
        {
            DxfPreview = LoadBitmap(DxfPreviewRenderer.RenderToPng(DxfPath, PreviewWidth));
        }
        catch
        {
            DxfPreview = null;
        }
    }

    private void RegenerateSvgPreview()
    {
        if (string.IsNullOrEmpty(SvgContent))
        {
            SvgPreview = null;
            return;
        }
        try
        {
            SvgPreview = LoadBitmap(SvgRasterizer.RenderToPng(SvgContent, PreviewWidth));
        }
        catch
        {
            SvgPreview = null;
        }
    }

    private void RegeneratePngPreview()
    {
        if (PngBytes is null)
        {
            PngPreview = null;
            return;
        }
        try
        {
            PngPreview = LoadBitmap(PngBytes);
        }
        catch
        {
            PngPreview = null;
        }
    }

    // ---- Persistence of transition parameters ----

    partial void OnFillColorChanged(string value)
    {
        if (_loaded)
        {
            _settings.Save(FillColorKey, value);
        }
    }

    partial void OnPngWidthChanged(int value)
    {
        if (_loaded)
        {
            _settings.Save<int>(PngWidthKey, value);
        }
    }

    // ---- Node uploads (setting the artifact regenerates its preview) ----

    public void LoadDxf(string path)
    {
        SourceBaseName = Path.GetFileNameWithoutExtension(path);
        DxfPath = path;
        Status = DxfPreview is null
            ? $"Loaded \"{Path.GetFileName(path)}\", but no preview could be generated (no drawable geometry?)."
            : $"Loaded DXF \"{Path.GetFileName(path)}\". Convert it to SVG.";
    }

    public void LoadSvg(string path)
    {
        try
        {
            SourceBaseName = Path.GetFileNameWithoutExtension(path);
            SvgContent = File.ReadAllText(path);
            Status = SvgPreview is null
                ? $"Loaded \"{Path.GetFileName(path)}\", but the SVG could not be rendered."
                : $"Loaded SVG \"{Path.GetFileName(path)}\". Render it to PNG.";
        }
        catch (Exception ex)
        {
            Status = $"Loading SVG failed: {ex.Message}";
        }
    }

    public void LoadPng(string path)
    {
        try
        {
            SourceBaseName = Path.GetFileNameWithoutExtension(path);
            PngBytes = File.ReadAllBytes(path);
            Status = PngPreview is null
                ? $"Loaded \"{Path.GetFileName(path)}\", but it is not a valid PNG."
                : $"Loaded PNG \"{Path.GetFileName(path)}\".";
        }
        catch (Exception ex)
        {
            Status = $"Loading PNG failed: {ex.Message}";
        }
    }

    // ---- Transitions ----

    public void ConvertDxfToSvg()
    {
        if (string.IsNullOrEmpty(DxfPath))
        {
            return;
        }
        try
        {
            string fill = string.IsNullOrWhiteSpace(FillColor) ? Converter.DefaultFill : FillColor;
            (string svg, int faceCount) = Converter.ConvertToSvg(DxfPath, fill);
            SvgContent = svg;
            Status = $"Converted to SVG: {faceCount} filled face(s).";
        }
        catch (Exception ex)
        {
            Status = $"DXF → SVG failed: {ex.Message}";
        }
    }

    public void ConvertSvgToPng()
    {
        if (string.IsNullOrEmpty(SvgContent))
        {
            return;
        }
        if (PngWidth <= 0)
        {
            Status = "PNG width must be a positive number.";
            return;
        }
        try
        {
            PngBytes = SvgRasterizer.RenderToPng(SvgContent, PngWidth);
            Status = $"Rendered PNG at {PngWidth}px wide.";
        }
        catch (Exception ex)
        {
            Status = $"SVG → PNG failed: {ex.Message}";
        }
    }

    // ---- Node transforms (setting the artifact regenerates its preview) ----

    public void RotateSvgClockwise()
    {
        if (string.IsNullOrEmpty(SvgContent))
        {
            return;
        }
        try
        {
            SvgContent = Transforms.RotateSvgClockwise90(SvgContent);
            Status = "Rotated SVG 90° clockwise.";
        }
        catch (Exception ex)
        {
            Status = $"Rotating SVG failed: {ex.Message}";
        }
    }

    public void RotatePngClockwise()
    {
        if (PngBytes is null)
        {
            return;
        }
        try
        {
            PngBytes = Transforms.RotatePngClockwise90(PngBytes);
            Status = "Rotated PNG 90° clockwise.";
        }
        catch (Exception ex)
        {
            Status = $"Rotating PNG failed: {ex.Message}";
        }
    }

    private static Bitmap LoadBitmap(byte[] png)
    {
        using var stream = new MemoryStream(png);
        return new Bitmap(stream);
    }
}
