using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using CommunityToolkit.Mvvm.ComponentModel;
using DXF_Converter_GUI.Services;
using DxfToSvg.Core;
using DxfToSvg.Core.Pipeline;
using DxfToSvg.Core.Pipeline.Transitions;

namespace DXF_Converter_GUI.ViewModels;

/// <summary>Orchestrates the pipeline: three <see cref="PreviewNodeViewModel"/> nodes (DXF, SVG,
/// PNG) joined by transitions. Each node is a self-contained unit — artifact, autogenerated
/// preview, rotate and download — surfaced through the shared <c>PreviewPanel</c> control, so this
/// type only handles the format-changing transitions between nodes and their parameters.
///
/// All conversions and previews go through a <see cref="PipelineRegistry"/> rather than calling
/// converters directly, so any transition is modularly replaceable and new formats/conversions are
/// a registration in the registry, not a change here.</summary>
public partial class MainWindowViewModel : ObservableObject
{
    private const string FillColorKey = "FillColor";
    private const string PngWidthKey = "PngWidth";

    private readonly UserPersistentData _settings = new("settings");
    private readonly PipelineRegistry _pipeline = PipelineRegistry.CreateDefault();

    /// <summary>Guards against writing back to disk while the constructor applies loaded values.</summary>
    private readonly bool _loaded;

    /// <summary>Aspect ratio (height / width) of the current SVG's drawable area, cached when the
    /// SVG node changes so the computed PNG height doesn't re-parse the SVG on every width tick.</summary>
    private double? _svgAspectRatio;

    public PreviewNodeViewModel DxfNode { get; }
    public PreviewNodeViewModel SvgNode { get; }
    public PreviewNodeViewModel PngNode { get; }

    public MainWindowViewModel()
    {
        DxfNode = new PreviewNodeViewModel("DXF", Format.Dxf, _pipeline, SetStatus);
        SvgNode = new PreviewNodeViewModel("SVG", Format.Svg, _pipeline, SetStatus);
        PngNode = new PreviewNodeViewModel("PNG", Format.Png, _pipeline, SetStatus);

        DxfNode.PropertyChanged += OnNodePropertyChanged;
        SvgNode.PropertyChanged += OnNodePropertyChanged;

        if (_settings.TryLoad(FillColorKey, out string? fill) && !string.IsNullOrWhiteSpace(fill))
        {
            FillColor = fill;
        }
        if (_settings.TryLoad<int>(PngWidthKey, out int width) && width > 0)
        {
            PngWidth = width;
        }
        _loaded = true;
    }

    // ---- Transition parameters ----

    [ObservableProperty]
    private string _fillColor = Converter.DefaultFill;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(PngComputedHeight))]
    [NotifyPropertyChangedFor(nameof(HasPngComputedHeight))]
    private int _pngWidth = 813;

    [ObservableProperty]
    private string _status = "Upload a DXF, SVG, or PNG to begin.";

    public bool CanConvertToSvg => DxfNode.HasArtifact;
    public bool CanConvertToPng => SvgNode.HasArtifact;

    /// <summary>The PNG height (px) the SVG→PNG step will produce at the current <see cref="PngWidth"/>,
    /// derived from the source SVG's aspect ratio. Null when there is no SVG to measure.</summary>
    public int? PngComputedHeight =>
        _svgAspectRatio is { } ratio && PngWidth > 0
            ? SvgRasterizer.HeightForWidth(ratio, PngWidth)
            : null;

    public bool HasPngComputedHeight => PngComputedHeight is not null;

    // ---- Node change propagation (enable/disable converts, recompute PNG height) ----

    private void OnNodePropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (ReferenceEquals(sender, DxfNode) && e.PropertyName == nameof(PreviewNodeViewModel.HasArtifact))
        {
            OnPropertyChanged(nameof(CanConvertToSvg));
        }
        else if (ReferenceEquals(sender, SvgNode))
        {
            if (e.PropertyName == nameof(PreviewNodeViewModel.HasArtifact))
            {
                OnPropertyChanged(nameof(CanConvertToPng));
            }
            else if (e.PropertyName == nameof(PreviewNodeViewModel.Artifact))
            {
                _svgAspectRatio = MeasureAspectRatio(SvgNode.Artifact);
                OnPropertyChanged(nameof(PngComputedHeight));
                OnPropertyChanged(nameof(HasPngComputedHeight));
            }
        }
    }

    /// <summary>Aspect ratio (height / width) of an SVG artifact, or null if it isn't an SVG or
    /// can't be measured. Feeds <see cref="PngComputedHeight"/>.</summary>
    private static double? MeasureAspectRatio(Artifact? artifact)
    {
        if (artifact is null || !artifact.Format.Equals(Format.Svg))
        {
            return null;
        }
        try
        {
            return SvgRasterizer.TryGetAspectRatio(artifact.AsText());
        }
        catch
        {
            return null;
        }
    }

    // ---- Persistence of transition parameters ----

    partial void OnFillColorChanged(string value)
    {
        if (_loaded)
        {
            _settings.Save(FillColorKey, value);
        }
    }

    partial void OnPngWidthChanged(int value)
    {
        if (_loaded)
        {
            _settings.Save<int>(PngWidthKey, value);
        }
    }

    // ---- Node uploads ----

    public void LoadDxf(string path) => LoadInto(DxfNode, path);
    public void LoadSvg(string path) => LoadInto(SvgNode, path);
    public void LoadPng(string path) => LoadInto(PngNode, path);

    private void LoadInto(PreviewNodeViewModel node, string path)
    {
        try
        {
            node.SuggestedBaseName = Path.GetFileNameWithoutExtension(path);
            node.FileName = Path.GetFileName(path);
            node.Artifact = Artifact.FromBytes(node.Format, File.ReadAllBytes(path));
            Status = node.Preview is null
                ? $"Loaded \"{Path.GetFileName(path)}\", but it could not be previewed."
                : $"Loaded {node.Title} \"{Path.GetFileName(path)}\".";
        }
        catch (Exception ex)
        {
            Status = $"Loading {node.Title} failed: {ex.Message}";
        }
    }

    // ---- Transitions (resolved from the registry, driven by parameter schema) ----

    public void ConvertDxfToSvg()
        => RunTransition(
            _pipeline.Find(Format.Dxf, Format.Svg),
            DxfNode,
            SvgNode,
            new Dictionary<string, object?> { [DxfToSvgTransition.FillKey] = FillColor });

    public void ConvertSvgToPng()
    {
        if (PngWidth <= 0)
        {
            Status = "PNG width must be a positive number.";
            return;
        }
        RunTransition(
            _pipeline.Find(Format.Svg, Format.Png),
            SvgNode,
            PngNode,
            new Dictionary<string, object?> { [SvgToPngTransition.WidthKey] = PngWidth });
    }

    /// <summary>Applies a resolved transition from one node to another and stores the result.
    /// Central error handling and status reporting for the format-changing conversions.</summary>
    private void RunTransition(
        ITransition? transition,
        PreviewNodeViewModel source,
        PreviewNodeViewModel target,
        IReadOnlyDictionary<string, object?> arguments)
    {
        if (transition is null)
        {
            Status = "No transition is registered for that conversion.";
            return;
        }
        if (source.Artifact is null)
        {
            return;
        }
        try
        {
            Artifact output = transition.Apply(source.Artifact, arguments);
            target.SuggestedBaseName = source.SuggestedBaseName;
            target.FileName = null; // produced by a transition, not loaded from a file
            target.Artifact = output;
            Status = $"{transition.Name}: produced {output.Format.DisplayName} ({FormatSize(output.Data.Length)}).";
        }
        catch (Exception ex)
        {
            Status = $"{transition.Name} failed: {ex.Message}";
        }
    }

    private void SetStatus(string status) => Status = status;

    private static string FormatSize(int bytes)
        => bytes < 1024 ? $"{bytes} B" : $"{bytes / 1024.0:0.#} KB";
}
