using System;
using System.Collections.Generic;
using System.IO;
using Avalonia.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using DXF_Converter_GUI.Services;
using DxfToSvg.Core;
using DxfToSvg.Core.Pipeline;
using DxfToSvg.Core.Pipeline.Transitions;

namespace DXF_Converter_GUI.ViewModels;

/// <summary>Drives the pipeline as three data nodes — DXF, SVG, PNG — joined by transitions.
///
/// All conversions and previews go through a <see cref="PipelineRegistry"/> rather than calling
/// converters directly, so any transition is modularly replaceable and new formats/conversions are
/// a registration in the registry, not a change here. The current three fixed nodes are just one
/// configuration of that general machinery.
///
/// The stored data model is the pipeline <see cref="Artifact"/>s and the transition parameters
/// (<see cref="FillColor"/>, <see cref="PngWidth"/>) only; the three preview bitmaps are always
/// regenerated from an artifact whenever it changes — see the <c>OnXArtifactChanged</c> hooks — and
/// are never assigned from anywhere else.</summary>
public partial class MainWindowViewModel : ObservableObject
{
    private const int PreviewWidth = 640;

    private const string FillColorKey = "FillColor";
    private const string PngWidthKey = "PngWidth";

    private static readonly IReadOnlyDictionary<string, object?> NoArguments =
        new Dictionary<string, object?>();

    private readonly UserPersistentData _settings = new("settings");
    private readonly PipelineRegistry _pipeline = PipelineRegistry.CreateDefault();

    /// <summary>Guards against writing back to disk while the constructor applies loaded values.</summary>
    private readonly bool _loaded;

    public MainWindowViewModel()
    {
        if (_settings.TryLoad(FillColorKey, out string? fill) && !string.IsNullOrWhiteSpace(fill))
        {
            FillColor = fill;
        }
        if (_settings.TryLoad<int>(PngWidthKey, out int width) && width > 0)
        {
            PngWidth = width;
        }
        _loaded = true;
    }

    // ---- Data model: pipeline artifacts (the nodes) ----

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasDxf))]
    [NotifyPropertyChangedFor(nameof(CanConvertToSvg))]
    private Artifact? _dxfArtifact;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasSvg))]
    [NotifyPropertyChangedFor(nameof(CanConvertToPng))]
    private Artifact? _svgArtifact;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasPng))]
    private Artifact? _pngArtifact;

    // ---- Data model: transition parameters ----

    [ObservableProperty]
    private string _fillColor = Converter.DefaultFill;

    [ObservableProperty]
    private int _pngWidth = 813;

    // ---- Autogenerated previews (derived from the artifacts above; see OnXArtifactChanged) ----

    [ObservableProperty]
    private Bitmap? _dxfPreview;

    [ObservableProperty]
    private Bitmap? _svgPreview;

    [ObservableProperty]
    private Bitmap? _pngPreview;

    [ObservableProperty]
    private string? _dxfFileName;

    [ObservableProperty]
    private string _status = "Upload a DXF, SVG, or PNG to begin.";

    /// <summary>File name (without extension) of the most recently loaded input, used to
    /// suggest download names.</summary>
    public string? SourceBaseName { get; private set; }

    public bool HasDxf => DxfArtifact is not null;
    public bool HasSvg => SvgArtifact is not null;
    public bool HasPng => PngArtifact is not null;
    public bool CanConvertToSvg => HasDxf;
    public bool CanConvertToPng => HasSvg;

    /// <summary>SVG text of the current SVG artifact, for the download handler. Null if none.</summary>
    public string? SvgContent => SvgArtifact?.AsText();

    /// <summary>PNG bytes of the current PNG artifact, for the download handler. Null if none.</summary>
    public byte[]? PngBytes => PngArtifact?.Data;

    // ---- Preview regeneration: the ONLY places the preview bitmaps are assigned ----

    partial void OnDxfArtifactChanged(Artifact? value) => DxfPreview = RenderPreview(value);
    partial void OnSvgArtifactChanged(Artifact? value) => SvgPreview = RenderPreview(value);
    partial void OnPngArtifactChanged(Artifact? value) => PngPreview = RenderPreview(value);

    private Bitmap? RenderPreview(Artifact? artifact)
    {
        if (artifact is null)
        {
            return null;
        }
        try
        {
            byte[]? png = _pipeline.RenderPreview(artifact, PreviewWidth);
            return png is null ? null : LoadBitmap(png);
        }
        catch
        {
            return null;
        }
    }

    // ---- Persistence of transition parameters ----

    partial void OnFillColorChanged(string value)
    {
        if (_loaded)
        {
            _settings.Save(FillColorKey, value);
        }
    }

    partial void OnPngWidthChanged(int value)
    {
        if (_loaded)
        {
            _settings.Save<int>(PngWidthKey, value);
        }
    }

    // ---- Node uploads (setting the artifact regenerates its preview) ----

    public void LoadDxf(string path)
    {
        try
        {
            SourceBaseName = Path.GetFileNameWithoutExtension(path);
            DxfFileName = Path.GetFileName(path);
            DxfArtifact = Artifact.FromBytes(Format.Dxf, File.ReadAllBytes(path));
            Status = DxfPreview is null
                ? $"Loaded \"{Path.GetFileName(path)}\", but no preview could be generated (no drawable geometry?)."
                : $"Loaded DXF \"{Path.GetFileName(path)}\". Convert it to SVG.";
        }
        catch (Exception ex)
        {
            Status = $"Loading DXF failed: {ex.Message}";
        }
    }

    public void LoadSvg(string path)
    {
        try
        {
            SourceBaseName = Path.GetFileNameWithoutExtension(path);
            SvgArtifact = Artifact.FromBytes(Format.Svg, File.ReadAllBytes(path));
            Status = SvgPreview is null
                ? $"Loaded \"{Path.GetFileName(path)}\", but the SVG could not be rendered."
                : $"Loaded SVG \"{Path.GetFileName(path)}\". Render it to PNG.";
        }
        catch (Exception ex)
        {
            Status = $"Loading SVG failed: {ex.Message}";
        }
    }

    public void LoadPng(string path)
    {
        try
        {
            SourceBaseName = Path.GetFileNameWithoutExtension(path);
            PngArtifact = Artifact.FromBytes(Format.Png, File.ReadAllBytes(path));
            Status = PngPreview is null
                ? $"Loaded \"{Path.GetFileName(path)}\", but it is not a valid PNG."
                : $"Loaded PNG \"{Path.GetFileName(path)}\".";
        }
        catch (Exception ex)
        {
            Status = $"Loading PNG failed: {ex.Message}";
        }
    }

    // ---- Transitions (resolved from the registry, driven by parameter schema) ----

    public void ConvertDxfToSvg()
        => RunTransition(
            _pipeline.Find(Format.Dxf, Format.Svg),
            DxfArtifact,
            artifact => SvgArtifact = artifact,
            new Dictionary<string, object?> { [DxfToSvgTransition.FillKey] = FillColor });

    public void ConvertSvgToPng()
    {
        if (PngWidth <= 0)
        {
            Status = "PNG width must be a positive number.";
            return;
        }
        RunTransition(
            _pipeline.Find(Format.Svg, Format.Png),
            SvgArtifact,
            artifact => PngArtifact = artifact,
            new Dictionary<string, object?> { [SvgToPngTransition.WidthKey] = PngWidth });
    }

    public void RotateSvgClockwise()
        => RunTransition(
            _pipeline.FindById(RotateSvgClockwiseTransition.TransitionId),
            SvgArtifact,
            artifact => SvgArtifact = artifact,
            NoArguments);

    public void RotatePngClockwise()
        => RunTransition(
            _pipeline.FindById(RotatePngClockwiseTransition.TransitionId),
            PngArtifact,
            artifact => PngArtifact = artifact,
            NoArguments);

    /// <summary>Applies a resolved transition to an input artifact and stores the result. Central
    /// error handling and status reporting for every conversion in the app.</summary>
    private void RunTransition(
        ITransition? transition,
        Artifact? input,
        Action<Artifact> store,
        IReadOnlyDictionary<string, object?> arguments)
    {
        if (transition is null)
        {
            Status = "No transition is registered for that conversion.";
            return;
        }
        if (input is null)
        {
            return;
        }
        try
        {
            Artifact output = transition.Apply(input, arguments);
            store(output);
            Status = $"{transition.Name}: produced {output.Format.DisplayName} ({FormatSize(output.Data.Length)}).";
        }
        catch (Exception ex)
        {
            Status = $"{transition.Name} failed: {ex.Message}";
        }
    }

    private static string FormatSize(int bytes)
        => bytes < 1024 ? $"{bytes} B" : $"{bytes / 1024.0:0.#} KB";

    private static Bitmap LoadBitmap(byte[] png)
    {
        using var stream = new MemoryStream(png);
        return new Bitmap(stream);
    }
}
