using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Avalonia.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using DxfToSvg.Core.Pipeline;

namespace DXF_Converter_GUI.ViewModels;

/// <summary>One node of the pipeline (DXF, SVG or PNG). Owns a single <see cref="Artifact"/>, keeps
/// an autogenerated <see cref="Preview"/> in sync with it, and knows how to rotate itself via the
/// registry. Rotate availability is discovered from the registry — a node can rotate exactly when a
/// same-format transition exists for its format — so adding rotation to a new format is purely a
/// registration.</summary>
public partial class PreviewNodeViewModel : ObservableObject, IPreviewNode
{
    private const int PreviewWidth = 640;

    private static readonly IReadOnlyDictionary<string, object?> NoArguments =
        new Dictionary<string, object?>();

    private readonly PipelineRegistry _pipeline;
    private readonly Action<string> _setStatus;
    private readonly string? _rotateTransitionId;

    public string Title { get; }
    public Format Format { get; }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasArtifact))]
    [NotifyPropertyChangedFor(nameof(CanRotate))]
    private Artifact? _artifact;

    [ObservableProperty]
    private Bitmap? _preview;

    [ObservableProperty]
    private string? _fileName;

    /// <summary>Suggested base name (no extension) for downloads; set by the orchestrator as the
    /// artifact flows through the pipeline.</summary>
    public string SuggestedBaseName { get; set; } = "output";

    public PreviewNodeViewModel(string title, Format format, PipelineRegistry pipeline, Action<string> setStatus)
    {
        Title = title;
        Format = format;
        _pipeline = pipeline;
        _setStatus = setStatus;
        // A node can rotate when a same-format transition (From == To == its format) is registered.
        _rotateTransitionId = pipeline.TransitionsFrom(format).FirstOrDefault(t => t.To.Equals(format))?.Id;
    }

    public bool HasArtifact => Artifact is not null;

    public bool CanRotate => HasArtifact && _rotateTransitionId is not null;

    partial void OnArtifactChanged(Artifact? value) => Preview = RenderPreview(value);

    public void RotateClockwise()
    {
        if (Artifact is null || _rotateTransitionId is null)
        {
            return;
        }
        ITransition? rotate = _pipeline.FindById(_rotateTransitionId);
        if (rotate is null)
        {
            return;
        }
        try
        {
            Artifact = rotate.Apply(Artifact, NoArguments);
            _setStatus($"Rotated {Format.DisplayName} 90° clockwise.");
        }
        catch (Exception ex)
        {
            _setStatus($"Rotating {Format.DisplayName} failed: {ex.Message}");
        }
    }

    private Bitmap? RenderPreview(Artifact? artifact)
    {
        if (artifact is null)
        {
            return null;
        }
        try
        {
            byte[]? png = _pipeline.RenderPreview(artifact, PreviewWidth);
            return png is null ? null : LoadBitmap(png);
        }
        catch
        {
            return null;
        }
    }

    private static Bitmap LoadBitmap(byte[] png)
    {
        using var stream = new MemoryStream(png);
        return new Bitmap(stream);
    }
}
