namespace DxfToSvg.Core.Pipeline;

/// <summary>Produces a PNG preview of an artifact of a given <see cref="Format"/>. Registering one
/// per format keeps previews autogenerated and lets a future format ship its own preview without
/// the UI knowing how to render it.</summary>
public interface IPreviewRenderer
{
    Format Format { get; }

    /// <summary>Renders <paramref name="artifact"/> to PNG bytes, sized to roughly
    /// <paramref name="width"/> pixels wide.</summary>
    byte[] RenderPng(Artifact artifact, int width);
}

/// <summary>Preview for DXF artifacts: the raw linework (see <see cref="DxfPreviewRenderer"/>).</summary>
public sealed class DxfPreview : IPreviewRenderer
{
    public Format Format => Format.Dxf;

    public byte[] RenderPng(Artifact artifact, int width)
        => DxfPreviewRenderer.RenderToPngFromContent(artifact.AsText(), width);
}

/// <summary>Preview for SVG artifacts: rasterize via <see cref="SvgRasterizer"/>.</summary>
public sealed class SvgPreview : IPreviewRenderer
{
    public Format Format => Format.Svg;

    public byte[] RenderPng(Artifact artifact, int width)
        => SvgRasterizer.RenderToPng(artifact.AsText(), width);
}

/// <summary>Preview for PNG artifacts: the bytes are already a PNG, so this is the identity.</summary>
public sealed class PngPreview : IPreviewRenderer
{
    public Format Format => Format.Png;

    public byte[] RenderPng(Artifact artifact, int width) => artifact.Data;
}
