using System.IO;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Platform.Storage;
using DXF_Converter_GUI.ViewModels;

namespace DXF_Converter_GUI.Controls;

/// <summary>Shared preview component: shows a node's autogenerated preview plus Rotate and Download
/// actions. Bound to an <see cref="IPreviewNode"/>, so every pipeline node (DXF, SVG, PNG, or any
/// future format) reuses it without duplicating the rotate/download wiring. The save dialog lives
/// here — driven entirely by the node's artifact and format — so the control is self-contained.</summary>
public partial class PreviewPanel : UserControl
{
    public PreviewPanel()
    {
        InitializeComponent();
    }

    private void OnRotate(object? sender, RoutedEventArgs e)
    {
        if (DataContext is IPreviewNode node)
        {
            node.RotateClockwise();
        }
    }

    private async void OnDownload(object? sender, RoutedEventArgs e)
    {
        if (DataContext is not IPreviewNode node || node.Artifact is null)
        {
            return;
        }
        TopLevel? top = TopLevel.GetTopLevel(this);
        if (top is null)
        {
            return;
        }

        var format = node.Artifact.Format;
        var fileType = new FilePickerFileType($"{format.DisplayName} files")
        {
            Patterns = new[] { $"*{format.Extension}" },
        };
        IStorageFile? file = await top.StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
        {
            Title = $"Save {format.DisplayName}",
            SuggestedFileName = node.SuggestedBaseName + format.Extension,
            DefaultExtension = format.Extension.TrimStart('.'),
            FileTypeChoices = new[] { fileType },
        });

        string? path = file?.TryGetLocalPath();
        if (path is not null)
        {
            await File.WriteAllBytesAsync(path, node.Artifact.Data);
        }
    }
}
